FROM golang:1.23 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cron_prepare ./cmd/cron_prepare

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/cron_prepare .
CMD ["./cron_prepare"]
