FROM rabbitmq:3.11-management

# Cài curl trước
RUN apt-get update && apt-get install -y curl

# Tải đúng plugin delayed message exchange
RUN curl -Lo /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.11.0.ez \
  https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.11.0/rabbitmq_delayed_message_exchange-3.11.0.ez

# Bật plugin
RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange
